import numpy as np
import pandas as pd
import polars as pl
from pyspark.sql.types import (
    FloatType,
    ShortType,
    StringType,
    StructField,
    StructType,
)

SCHEMA_PANDAS = {
    # strings
    "id_basica": str,
    "id_empresa": str,
    "id_tipo_linha": str,
    "id_arquivo": str,
    "id_di": str,
    "cd_di": str,
    "nr_ano_mes_referencia": str,
    "nr_chave": str,
    "nr_singular": str,
    # ints (nullable to handle NA values in CSV)
    "nr_decolagem": pd.Int8Dtype(),
    "nr_mes_referencia": pd.Int16Dtype(),
    "nr_dia_referencia": pd.Int8Dtype(),
    "nr_voo": pd.Int16Dtype(),
    "nr_semestre_referencia": pd.Int16Dtype(),
    "nr_trimestre_referencia": pd.Int8Dtype(),
    "nr_semana_referencia": pd.Int8Dtype(),
    "nr_escala_destino": pd.Int16Dtype(),
    # floats
    "lt_combustivel": np.float16,
    "kg_payload": np.float16,
    "km_distancia": np.float16,
    "kg_bagagem_livre": np.float16,
    "kg_bagagem_excesso": np.float16,
    "kg_carga_paga": np.float16,
    "kg_carga_gratis": np.float16,
    "kg_correio": np.float16,
    "kg_peso": np.float16,
    "nr_pax_gratis_km": np.float16,
    "nr_carga_gratis_km": np.float16,
    "nr_correio_km": np.float16,
    "nr_bagagem_paga_km": np.float16,
    "nr_ask": np.float16,
    "nr_rpk": np.float16,
    "nr_atk": np.float16,
    "nr_rtk": np.float16,
    # to convert later
    "nr_horas_voadas": str,
    "nr_velocidade_media": str,
    "nr_ano_partida_real": str,
    "nr_semestre_partida_real": str,
    "nr_trimestre_partida_real": str,
    "nr_assentos_ofertados": str,
    "nr_passag_pagos": str,
    "nr_passag_gratis": str,
    "nr_linha": str,
    "nr_carga_paga_km": str,
    "nr_bagagem_gratis_km": str,
}


SCHEMA = {
    # ---- strings ----
    "id_basica": pl.Utf8,
    "id_empresa": pl.Utf8,
    "id_tipo_linha": pl.Utf8,
    "id_arquivo": pl.Utf8,
    "id_di": pl.Utf8,
    "cd_di": pl.Utf8,
    "nr_ano_mes_referencia": pl.Utf8,
    "nr_chave": pl.Utf8,
    "nr_singular": pl.Utf8,
    # ---- ints ----
    "nr_decolagem": pl.Int8,
    "nr_mes_referencia": pl.Int16,
    "nr_dia_referencia": pl.Int8,
    "nr_voo": pl.Int16,
    "nr_semestre_referencia": pl.Int16,
    "nr_trimestre_referencia": pl.Int8,
    "nr_semana_referencia": pl.Int8,
    "nr_escala_destino": pl.Int16,
    # ---- floats (sem vírgula) ----
    "lt_combustivel": pl.Float16,
    "kg_payload": pl.Float16,
    "km_distancia": pl.Float16,
    "kg_bagagem_livre": pl.Float16,
    "kg_bagagem_excesso": pl.Float16,
    "kg_carga_paga": pl.Float16,
    "kg_carga_gratis": pl.Float16,
    "kg_correio": pl.Float16,
    "kg_peso": pl.Float16,
    "nr_pax_gratis_km": pl.Float16,
    "nr_carga_gratis_km": pl.Float16,
    "nr_correio_km": pl.Float16,
    "nr_bagagem_paga_km": pl.Float16,
    "nr_ask": pl.Float16,
    "nr_rpk": pl.Float16,
    "nr_atk": pl.Float16,
    "nr_rtk": pl.Float16,
    # ---- converter depois ----
    "nr_horas_voadas": pl.Utf8,
    "nr_velocidade_media": pl.Utf8,
    "nr_ano_partida_real": pl.Utf8,
    "nr_semestre_partida_real": pl.Utf8,
    "nr_trimestre_partida_real": pl.Utf8,
    "nr_assentos_ofertados": pl.Utf8,
    "nr_passag_pagos": pl.Utf8,
    "nr_passag_gratis": pl.Utf8,
    "nr_linha": pl.Utf8,
    "nr_carga_paga_km": pl.Utf8,
    "nr_bagagem_gratis_km": pl.Utf8,
}

SCHEMA_SPARK = StructType(
    [
        # ---- strings ----
        StructField("id_basica", StringType(), True),
        StructField("id_empresa", StringType(), True),
        StructField("id_tipo_linha", StringType(), True),
        StructField("id_arquivo", StringType(), True),
        StructField("id_di", StringType(), True),
        StructField("cd_di", StringType(), True),
        StructField("nr_ano_mes_referencia", StringType(), True),
        StructField("nr_chave", StringType(), True),
        StructField("nr_singular", StringType(), True),
        # ---- ints ----
        StructField("nr_decolagem", ShortType(), True),
        StructField("nr_mes_referencia", ShortType(), True),
        StructField("nr_dia_referencia", ShortType(), True),
        StructField("nr_voo", ShortType(), True),
        StructField("nr_semestre_referencia", ShortType(), True),
        StructField("nr_trimestre_referencia", ShortType(), True),
        StructField("nr_semana_referencia", ShortType(), True),
        StructField("nr_escala_destino", ShortType(), True),
        # ---- floats ----
        StructField("lt_combustivel", FloatType(), True),
        StructField("kg_payload", FloatType(), True),
        StructField("km_distancia", FloatType(), True),
        StructField("kg_bagagem_livre", FloatType(), True),
        StructField("kg_bagagem_excesso", FloatType(), True),
        StructField("kg_carga_paga", FloatType(), True),
        StructField("kg_carga_gratis", FloatType(), True),
        StructField("kg_correio", FloatType(), True),
        StructField("kg_peso", FloatType(), True),
        StructField("nr_pax_gratis_km", FloatType(), True),
        StructField("nr_carga_gratis_km", FloatType(), True),
        StructField("nr_correio_km", FloatType(), True),
        StructField("nr_bagagem_paga_km", FloatType(), True),
        StructField("nr_ask", FloatType(), True),
        StructField("nr_rpk", FloatType(), True),
        StructField("nr_atk", FloatType(), True),
        StructField("nr_rtk", FloatType(), True),
        # ---- converter depois (keeping as string) ----
        StructField("nr_horas_voadas", StringType(), True),
        StructField("nr_velocidade_media", StringType(), True),
        StructField("nr_ano_partida_real", StringType(), True),
        StructField("nr_semestre_partida_real", StringType(), True),
        StructField("nr_trimestre_partida_real", StringType(), True),
        StructField("nr_assentos_ofertados", StringType(), True),
        StructField("nr_passag_pagos", StringType(), True),
        StructField("nr_passag_gratis", StringType(), True),
        StructField("nr_linha", StringType(), True),
        StructField("nr_carga_paga_km", StringType(), True),
        StructField("nr_bagagem_gratis_km", StringType(), True),
    ]
)
