---
raw:
  path: data/raw/
  filename: anac_brazil.csv
  sample_path: data/raw/sample/
silver:
  path: data/silver/
kaggle:
  dataset: sturarods/anac-national-civil-aviation-agency-2000-2025
  force_download: false
visualization:
  output_path: docs/plots/
postgres:
  host: postgres
  port: 5432
  database: lab_02_db
  user: user
  password: 123
